image: node

pipelines:
  branches:
    main: # This specifies that the following steps should only run on the main branch
      - step:
          name: Test
          script:
            - npm install

      - step:
          name: Build
          script:
            - npm install && npm run build
          artifacts:
            - build/**

      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:0.2.4
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT